name: 🐧 Linux Builds 4
on:
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * *'


# Global Settings
env:
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: debug_symbols=yes CCFLAGS="-fpie" LINKFLAGS="-no-pie"

jobs:
  build-godot4:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
#          - name: Editor Mono Sanitizers
#            cache-name: linux4-editor-mono-sanitizers
#            target: debug
#            tools: true
#            sconsflags: module_mono_enabled=yes mono_glue=no use_ubsan=yes use_asan=yes tests=yes
#            build-mono: true
#            bin: "./bin/godot.linuxbsd.tools.64s.mono"
#            artifact: true

          - name: Editor Sanitizers
            cache-name: linux4-editor-sanitizers
            target: debug
            tools: true
            sconsflags: use_ubsan=yes use_asan=yes tests=yes
            bin: "./bin/godot.linuxbsd.tools.64s"
            artifact: true

          - name: Editor64 Sanitizers
            cache-name: linux4-editor64-sanitizers
            target: debug
            tools: true
            sconsflags: use_ubsan=yes use_asan=yes tests=yes float=64
            bin: "./bin/godot.linuxbsd.tools.64s"
            artifact: true
            
          - name: Template Release Sanitizers
            cache-name: linux4-template-sanitizers
            target: release
            tools: false
            sconsflags: use_ubsan=yes use_asan=yes optimize=none
            bin: "./bin/godot.linuxbsd.opt.64s"
            artifact: true
            
#          - name: Editor Mono Normal
#            cache-name: linux4-editor-mono-normal
#            target: debug
#            tools: true
#            sconsflags: module_mono_enabled=yes mono_glue=no tests=yes
#            build-mono: true
#            bin: "./bin/godot.linuxbsd.tools.64.mono"
#            artifact: true

          - name: Editor Normal
            cache-name: linux4-editor-normal
            target: debug
            tools: true
            sconsflags: tests=yes
            bin: "./bin/godot.linuxbsd.tools.64"
            artifact: true

          - name: Editor64 Normal
            cache-name: linux4-editor64-normal
            target: debug
            tools: true
            sconsflags: tests=yes float=64
            bin: "./bin/godot.linuxbsd.tools.64"
            artifact: true
            
          - name: Template Release Normal
            cache-name: linux4-template-normal
            target: release
            tools: false
            sconsflags: optimize=none
            bin: "./bin/godot.linuxbsd.opt.64"
            artifact: true
            
#          - name: Editor Mono Sanitizers LLVM
#            cache-name: linux4-editor-mono-sanitizers-llvm
#            target: debug
#            tools: true
#            tests: false
#            sconsflags: module_mono_enabled=yes mono_glue=no use_ubsan=yes use_asan=yes use_llvm=yes
#            build-mono: true
#            bin: "./bin/godot.linuxbsd.tools.64.llvms.mono"
#            artifact: true
#
#          - name: Editor Sanitizers LLVM
#            cache-name: linux4-editor-sanitizers-llvm
#            target: debug
#            tools: true
#            tests: false
#            sconsflags: use_ubsan=yes use_asan=yes use_llvm=yes
#            bin: "./bin/godot.linuxbsd.tools.64.llvms"
#            artifact: true
#            
#          - name: Template Release Sanitizers LLVM
#            cache-name: linux4-template-sanitizers-llvm
#            target: release
#            tools: false
#            tests: false
#            sconsflags: use_ubsan=yes use_asan=yes use_llvm=yes optimize=none
#            bin: "./bin/godot.linuxbsd.opt.64.llvms"
#            artifact: true

          - name: Editor Minimal
            cache-name: linux4-editor-minimal
            target: debug
            tools: true
            sconsflags: module_basis_universal_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no module_denoise_enabled=no module_enet_enabled=no module_etcpak_enabled=no brotli=no module_glslang_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_jpg_enabled=no module_jsonrpc_enabled=no module_lightmapper_rd_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_regex_enabled=no module_squish_enabled=no module_svg_enabled=no graphite=no module_text_server_adv_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webp_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no # module_freetype_enabled=no - cannot compile,  module_navigation_enabled=no - crash, module_gdscript_enabled=no, wanna to run scripts, module_regex_enabled=no - bug in project converter
            bin: "./bin/godot.linuxbsd.tools.64"
            artifact: true

          - name: Editor Minimal Sanitizers
            cache-name: linux4-editor-minimal-sanitizers
            target: debug
            tools: true
            sconsflags: module_basis_universal_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no module_denoise_enabled=no module_enet_enabled=no module_etcpak_enabled=no brotli=no module_glslang_enabled=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_jpg_enabled=no module_jsonrpc_enabled=no module_lightmapper_rd_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_squish_enabled=no module_svg_enabled=no graphite=no module_text_server_adv_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webp_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no use_ubsan=yes use_asan=yes # module_freetype_enabled=no - cannot compile,  module_navigation_enabled=no - crash, module_gdscript_enabled=no, wanna to run scripts, module_regex_enabled=no - bug in project converter
            bin: "./bin/godot.linuxbsd.tools.64"
            artifact: true

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: ${{ env.GODOT_BASE_BRANCH }}
          path: godot

      - name: Linux dependencies
        shell: bash
        run: |
          # Azure repositories are not reliable, we need to prevent azure giving us packages.
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update
          # The actual dependencies
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
              libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
              libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        run: |
          ls
          cd godot
          scons ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} target=${{ matrix.target }} tools=${{ matrix.tools }} -j2
          cd ..
          
      # Generate mono glue
      - name: Mono Glue Generator
        if: ${{ matrix.build-mono }}
        run: |
          cd godot
          ${{ matrix.bin }} --headless --generate-mono-glue modules/mono/glue || true
          cd ..

      # Rebuild with mono
      - name: Compilation Mono Glue
        if: ${{ matrix.build-mono }}
        run: |
          cd godot
          scons ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} target=${{ matrix.target }} tools=${{ matrix.tools }} mono_glue=yes -j2
          ls bin/
          cd ..

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: ${{ matrix.artifact }}
        with:
          name: ${{ matrix.cache-name }}

