name: 🪟️ Windows Builds 4
on:
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * *'


env:
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: dev_build=yes

jobs:
  build-godot4:
    runs-on: "windows-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor Normal
            cache-name: windows4-editor-normal
            target: editor
            sconsflags: p=windows
            artifact: true

          - name: Editor Sanitizers
            cache-name: windows4-editor-sanitizers
            target: editor
            sconsflags: p=windows
            artifact: true

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          ref: ${{ env.GODOT_BASE_BRANCH }}
          path: godot

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons pywin32
          python --version
          scons --version

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        run: |
          ls
          cd godot
          scons ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }} target=${{ matrix.target }} -j2
          cd ..
          
      - name: Compilation
        env:
          SCONS_CACHE: /.scons_cache/
        run: |
          scons -j2 verbose=yes warnings=all werror=yes tests=no target=${{matrix.target}} dev_build=no
      # Make build available
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.executable_name}}
          path: bin/

